/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7_pcd;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author usuario
 */
public class Generador extends java.awt.Frame {

    /**
     * Creates new form Generador
     */
    public Generador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        Random aleatorio = new Random();
        ArrayList<Thread> Practicas = new ArrayList<>();
        ArrayList<EstudianteTeoria> Teorias = new ArrayList<>();
        Despacho mi_Despacho = new Despacho();
        
        Generador vPrincipal = new Generador();
        vPrincipal.setSize(1280, 768);
        CanvasGenerador cv = new CanvasGenerador();
        vPrincipal.add(cv);
        vPrincipal.setVisible(true);
        
        for (int i = 0; i < 20; i++) {
            int porcentaje = aleatorio.nextInt(100);
            
            if(porcentaje < 30){
                Thread h1 = new Thread(new EstudiantePracticas(mi_Despacho, cv));
                Practicas.add(h1);
                h1.start();
            }else{
                EstudianteTeoria T1 = new EstudianteTeoria(mi_Despacho, cv);
                Teorias.add(T1);
                T1.start();
            }
            
            //System.out.println(i);
        }
        
        for (int i = 0; i < Practicas.size(); i++) {
            Practicas.get(i).join();
        }
        
        for (int i = 0; i < Teorias.size(); i++) {
            Teorias.get(i).join();
        }
        
        System.exit(0);
        
        /*Despacho mi_Despacho = new Despacho();
        EstudianteTeoria T1 = new EstudianteTeoria(mi_Despacho);
        T1.start();
        EstudianteTeoria T2 = new EstudianteTeoria(mi_Despacho);
        T2.start();
        EstudianteTeoria T3 = new EstudianteTeoria(mi_Despacho);
        T3.start();
        Thread P1 = new Thread(new EstudiantePracticas(mi_Despacho));
        P1.start();
        
        T1.join();
        T2.join();
        T3.join();
        P1.join();*/
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
